"""Direct Human release authorization acceptance.

The preview is always generated by the real Store/Executor command.  Tests
seed only candidate-bound upstream evidence, then use the real CLI decision
surface to observe authorization or rejection.
"""

from __future__ import annotations

import hashlib
import subprocess
from pathlib import Path

import pytest

from tests.integration.test_release_preview_direct import (
    _events,
    _git,
    _issue_preview,
    _prepare,
    _previews,
)
from tracks import paths
from tracks.executor.m_verify import freeze_candidate
from tracks.store import Store

pytestmark = pytest.mark.integration


def _append_gate_failure(store: Store, run_id: str, candidate: str, contract_digest: str) -> None:
    store.append(
        run_id,
        store.state(run_id).version or "v0.8",
        "local_gate.failed",
        {
            "kind": "trace",
            "gate_identity": "trace[1]",
            "candidate_sha": candidate,
            "contract_digest": contract_digest,
            "command_echo": ["true"],
            "normalized_result": {
                "schema": "tracks-gate-result",
                "version": 1,
                "status": "failed",
                "exit_code": 7,
                "summary": {"source": "accepted upstream failure premise"},
                "gate_id": "trace",
            },
            "status": "failed",
            "exit_code": 7,
            "reason": "failed",
        },
    )


def _append_ci(
    store: Store,
    run_id: str,
    candidate: str,
    *,
    status: str = "passed",
    head_sha: str | None = None,
) -> None:
    store.append(
        run_id,
        store.state(run_id).version or "v0.8",
        "ci.run_observed",
        {
            "status": status,
            "repo": "local/preview-host",
            "workflow": "123",
            "run_id": 18,
            "head_sha": head_sha or candidate,
            "candidate_sha": candidate,
            "conclusion": "success" if status == "passed" else "failure",
            "required_checks": ["required-ci"],
            "api_verified": True,
        },
    )


def _append_complete_recovery(
    store: Store, run_id: str, candidate: str, contract_digest: str, artifact_digest: str
) -> None:
    """Append later same-candidate evidence without minting a second freeze."""
    version = store.state(run_id).version or "v0.8"
    for ordinal, kind in enumerate(("quality", "trace")):
        store.append(
            run_id,
            version,
            "local_gate.passed",
            {
                "kind": kind,
                "gate_identity": f"{kind}[{ordinal}]",
                "candidate_sha": candidate,
                "contract_digest": contract_digest,
                "command_echo": ["true", "recovery"],
                "normalized_result": {
                    "schema": "tracks-gate-result",
                    "version": 1,
                    "status": "passed",
                    "exit_code": 0,
                    "summary": {"source": "accepted recovery premise"},
                    "gate_id": kind,
                },
                "status": "passed",
                "exit_code": 0,
            },
        )
    store.append(
        run_id,
        version,
        "artifact.built",
        {
            "candidate_sha": candidate,
            "artifact": "dist/package.whl",
            "artifact_digest": artifact_digest,
            "status": "passed",
        },
    )
    _append_ci(store, run_id, candidate)
    store.append(
        run_id,
        version,
        "prism.verdict",
        {
            "verdict": "pass",
            "scope": "verify_final",
            "candidate_sha": candidate,
            "evidence_digests": {"artifact": artifact_digest},
        },
    )
    review_command_id = f"security-review-{candidate}"
    store.append(
        run_id,
        version,
        "prism.verdict",
        {
            "verdict": "pass",
            "scope": "security",
            "candidate_sha": candidate,
            "policy_digest": contract_digest,
            "evidence_digests": {"artifact": artifact_digest},
        },
        command_id=review_command_id,
    )
    store.append(
        run_id,
        version,
        "security.assessed",
        {
            "status": "passed",
            "policy_digest": contract_digest,
            "candidate_sha": candidate,
            "scans": [{"id": "accepted-recovery", "status": "passed"}],
            "prism_scope": "security",
            "review_command_id": review_command_id,
        },
    )


def _new_candidate(
    repo: Path,
    run_id: str,
    contract: Path,
    artifact_digest: str,
    *,
    include_ci: bool = True,
    remote: Path | None = None,
) -> tuple[str, str]:
    """Create and freeze a clean new candidate, then seed upstream premises."""
    marker = repo / "candidate-marker.txt"
    marker.write_text("new candidate\n", encoding="utf-8")
    subprocess.run(["git", "add", "candidate-marker.txt"], cwd=repo, check=True, capture_output=True)
    _git(repo, "commit", "-qm", "new candidate for authorization premise")
    candidate = _git(repo, "rev-parse", "HEAD")
    identity = freeze_candidate(repo)
    assert identity.candidate_sha == candidate and identity.clean_tree
    if remote is not None:
        _git(repo, "push", "-q", "origin", "HEAD:refs/heads/main")

    contract_digest = hashlib.sha256(contract.read_bytes()).hexdigest()
    store = Store(paths.tracks_home(repo))
    try:
        version = store.state(run_id).version or "v0.8"
        store.append(run_id, version, "stage.entered", {"stage": "M-VERIFY"})
        store.append(
            run_id,
            version,
            "candidate.frozen",
            {
                "candidate_sha": candidate,
                "clean_tree": True,
                "branch": identity.branch,
                "frozen_at_seq": len(list(store.events(run_id))) + 1,
            },
        )
        for ordinal, kind in enumerate(("quality", "trace")):
            store.append(
                run_id,
                version,
                "local_gate.passed",
                {
                    "kind": kind,
                    "gate_identity": f"{kind}[{ordinal}]",
                    "candidate_sha": candidate,
                    "contract_digest": contract_digest,
                    "command_echo": ["true"],
                    "normalized_result": {
                        "schema": "tracks-gate-result",
                        "version": 1,
                        "status": "passed",
                        "exit_code": 0,
                        "summary": {"source": "accepted upstream premise"},
                        "gate_id": kind,
                    },
                    "status": "passed",
                    "exit_code": 0,
                },
            )
        store.append(
            run_id,
            version,
            "artifact.built",
            {
                "candidate_sha": candidate,
                "artifact": "dist/package.whl",
                "artifact_digest": artifact_digest,
                "status": "passed",
            },
        )
        if include_ci:
            _append_ci(store, run_id, candidate)
        store.append(
            run_id,
            version,
            "prism.verdict",
            {
                "verdict": "pass",
                "scope": "verify_final",
                "candidate_sha": candidate,
                "evidence_digests": {"artifact": artifact_digest},
            },
        )
        review_command_id = f"security-review-{candidate}"
        store.append(
            run_id,
            version,
            "prism.verdict",
            {
                "verdict": "pass",
                "scope": "security",
                "candidate_sha": candidate,
                "policy_digest": contract_digest,
                "evidence_digests": {"artifact": artifact_digest},
            },
            command_id=review_command_id,
        )
        store.append(
            run_id,
            version,
            "security.assessed",
            {
                "status": "passed",
                "policy_digest": contract_digest,
                "candidate_sha": candidate,
                "scans": [{"id": "accepted-upstream", "status": "passed"}],
                "prism_scope": "security",
                "review_command_id": review_command_id,
            },
        )
        store.append(run_id, version, "stage.exited", {"stage": "M-VERIFY"})
        store.append(run_id, version, "stage.entered", {"stage": "M-SECURITY"})
        store.append(run_id, version, "stage.exited", {"stage": "M-SECURITY"})
        store.append(run_id, version, "stage.entered", {"stage": "M-RELEASE"})
    finally:
        store.close()
    return candidate, contract_digest


def _assert_preview_blob(repo: Path, run_id: str, candidate: str) -> dict:
    previews = _previews(_events(repo, run_id))
    assert previews, "real generate_preview must emit release.previewed"
    payload = previews[-1].payload
    assert payload.get("candidate_sha") == candidate
    for field in (
        "preview_digest",
        "artifact_digest",
        "evidence_digests",
        "operation_plan_digest",
        "contract_policy_digest",
        "blob_ref",
    ):
        assert payload.get(field) not in (None, ""), f"preview field missing: {field}"
    store = Store(paths.tracks_home(repo))
    try:
        blob = store.load_payload({"$ref": Path(payload["blob_ref"]).name})
    finally:
        store.close()
    assert blob == {key: value for key, value in payload.items() if key != "blob_ref"}
    return payload


def _release(trac, action: str, *, stale_target: str | None = None):
    args = ["release", "--action", action]
    if action == "return":
        args.extend(["--to", stale_target or "M-DESIGN"])
    args.extend(["--reason", "authorization acceptance premise"])
    return trac(*args)


# AC-FR0274-01: one complete, same-candidate chain can be authorized by the
# Human CLI, and the decision is the real release.decided result.
def test_same_candidate_complete_chain_authorizes(host_repo, trac, tmp_path):
    run_id, candidate, _contract, _remote, _artifact_digest, _contract_digest = _prepare(
        host_repo, trac, tmp_path
    )
    _issue_preview(host_repo, run_id, candidate)
    preview = _assert_preview_blob(host_repo, run_id, candidate)
    result = _release(trac, "release")
    assert result.returncode == 0, result.stderr
    decisions = [event for event in _events(host_repo, run_id) if event.type == "release.decided"]
    assert decisions and decisions[-1].payload == {
        "action": "release",
        "candidate_sha": candidate,
        "preview_digest": preview["preview_digest"],
        "reason": "authorization acceptance premise",
        "target": None,
        "actor": "human",
    }


@pytest.mark.parametrize("invalid_case", ["foreign", "missing", "ci_failed"])
# AC-FR0274-02: foreign, missing, and failed current-candidate CI evidence all
# reject without a successful release decision.
def test_invalid_candidate_bound_evidence_rejects(host_repo, trac, tmp_path, invalid_case):
    run_id, candidate, contract, remote, artifact_digest, contract_digest = _prepare(
        host_repo, trac, tmp_path
    )
    if invalid_case in {"foreign", "missing"}:
        candidate, contract_digest = _new_candidate(
            host_repo,
            run_id,
            contract,
            artifact_digest,
            include_ci=False,
            remote=remote,
        )
        if invalid_case == "foreign":
            store = Store(paths.tracks_home(host_repo))
            try:
                # The old candidate has valid CI; the new candidate has only
                # this unrelated CI record and must remain unbound.
                _append_ci(store, run_id, "f" * 40, head_sha="f" * 40)
            finally:
                store.close()
        _issue_preview(host_repo, run_id, candidate)
        _assert_preview_blob(host_repo, run_id, candidate)
    elif invalid_case == "ci_failed":
        _issue_preview(host_repo, run_id, candidate)
        _assert_preview_blob(host_repo, run_id, candidate)
        store = Store(paths.tracks_home(host_repo))
        try:
            _append_ci(store, run_id, candidate, status="failed")
        finally:
            store.close()
    result = _release(trac, "release")
    assert result.returncode != 0
    events = _events(host_repo, run_id)
    assert not any(
        event.type == "release.decided" and (event.payload or {}).get("action") == "release"
        for event in events
    )
    assert any(event.type == "release.rejected" for event in events)


@pytest.mark.parametrize("recovery_case", ["same_candidate", "new_candidate"])
# AC-FR0274-01/FR-0286: an old failure must not poison a complete current
# candidate recovery, whether the repair keeps or changes the candidate.
def test_old_failure_does_not_poison_recovery(host_repo, trac, tmp_path, recovery_case):
    run_id, candidate, contract, remote, artifact_digest, contract_digest = _prepare(
        host_repo, trac, tmp_path
    )
    store = Store(paths.tracks_home(host_repo))
    try:
        _append_gate_failure(store, run_id, candidate, contract_digest)
        if recovery_case == "same_candidate":
            _append_complete_recovery(store, run_id, candidate, contract_digest, artifact_digest)
            current_candidate = candidate
        else:
            current_candidate = None
    finally:
        store.close()
    if recovery_case == "new_candidate":
        current_candidate, contract_digest = _new_candidate(
            host_repo, run_id, contract, artifact_digest, remote=remote
        )
    _issue_preview(host_repo, run_id, current_candidate)
    _assert_preview_blob(host_repo, run_id, current_candidate)
    result = _release(trac, "release")
    assert result.returncode == 0, result.stderr
    decisions = [event for event in _events(host_repo, run_id) if event.type == "release.decided"]
    assert decisions and decisions[-1].payload["candidate_sha"] == current_candidate


@pytest.mark.parametrize("mutation", ["evidence", "contract"])
# AC-FR0273-02: changing evidence or contract inputs after preview makes the
# preview stale before any Human action is accepted.
def test_post_preview_inputs_are_reported_stale(host_repo, trac, tmp_path, mutation):
    run_id, candidate, contract, _remote, _artifact_digest, contract_digest = _prepare(
        host_repo, trac, tmp_path
    )
    _issue_preview(host_repo, run_id, candidate)
    _assert_preview_blob(host_repo, run_id, candidate)
    if mutation == "evidence":
        store = Store(paths.tracks_home(host_repo))
        try:
            store.append(
                run_id,
                store.state(run_id).version or "v0.8",
                "local_gate.passed",
                {
                    "kind": "trace",
                    "gate_identity": "trace[1]",
                    "candidate_sha": candidate,
                    "contract_digest": contract_digest,
                    "command_echo": ["true", "changed"],
                    "normalized_result": {
                        "schema": "tracks-gate-result",
                        "version": 1,
                        "status": "passed",
                        "exit_code": 0,
                        "summary": {"changed": True},
                        "gate_id": "trace",
                    },
                    "status": "passed",
                    "exit_code": 0,
                },
            )
        finally:
            store.close()
    else:
        contract.write_text(
            contract.read_text(encoding="utf-8").replace(
                'feature_tag = "v{minor}.0"', 'feature_tag = "v{minor}.1"'
            ),
            encoding="utf-8",
        )
    preview = trac("release", "preview")
    assert preview.returncode == 0
    assert "status=stale" in preview.stdout
    assert "stale_reason=" in preview.stdout
    rejected = _release(trac, "release")
    assert rejected.returncode != 0
    assert not any(
        event.type == "release.decided" for event in _events(host_repo, run_id)
    )


@pytest.mark.parametrize("action", ["release", "delay", "return"])
# AC-FR0274-04: every Human action rejects a stale preview and leaves no
# release.decided authorization event.
def test_all_human_actions_reject_stale_preview(host_repo, trac, tmp_path, action):
    run_id, candidate, _contract, _remote, _artifact_digest, contract_digest = _prepare(
        host_repo, trac, tmp_path
    )
    _issue_preview(host_repo, run_id, candidate)
    _assert_preview_blob(host_repo, run_id, candidate)
    store = Store(paths.tracks_home(host_repo))
    try:
        store.append(
            run_id,
            store.state(run_id).version or "v0.8",
            "local_gate.passed",
            {
                "kind": "trace",
                "gate_identity": "trace[1]",
                "candidate_sha": candidate,
                "contract_digest": contract_digest,
                "command_echo": ["true", "changed"],
                "normalized_result": {
                    "schema": "tracks-gate-result",
                    "version": 1,
                    "status": "passed",
                    "exit_code": 0,
                    "summary": {"changed": True},
                    "gate_id": "trace",
                },
                "status": "passed",
                "exit_code": 0,
            },
        )
    finally:
        store.close()
    result = _release(trac, action)
    assert result.returncode != 0
    assert not any(event.type == "release.decided" for event in _events(host_repo, run_id))
