"""Integration: Phase 0 hard-gate counterexample (§10.3 / IF-GUARD-001/002).

AC-FR0257-02@v0.7 guard hardened, no --exit-zero soft bypass,
AC-FR0258-01@v0.7 registry single source, eight categories.

§10.3 existing-asset update: the guard-registry-generated pre-commit hook is a
HARD gate — a lint violation is rejected (non-zero) and the hook command carries
NO ``--exit-zero`` (no soft guard / no bypass). Assertions land on the
``load_guard_registry``/``validate_guard_registry``/``deploy_guard_configs``/
``check_parity`` outlets (IF-GUARD-001/002, interfaces §1e/§1k). The stubs
raise NotImplementedError -> legal Red.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from tracks.executor.guard_registry import (
    check_parity,
    deploy_guard_configs,
    load_guard_registry,
    validate_guard_registry,
)

REPO = Path(__file__).resolve().parents[2]
ARCH = REPO / ".tracks" / "projects" / "v0.7" / "architecture.md"

pytestmark = pytest.mark.integration


# AC-FR0257-02@v0.7 TRACKS-TRACE hard gate: lint violation rejected, no --exit-zero
# AC-FR0258-01@v0.7 TRACKS-TRACE registry single source, eight categories
def test_phase0_hard_gate_rejects_violation_no_exit_zero(tmp_path):
    """§10.3 / Phase 0 hardening: the guard-registry-generated pre-commit hook
    is a HARD gate — a lint violation is rejected (non-zero) and the hook
    command carries NO ``--exit-zero`` (no soft guard / no bypass).

    Bound to IF-GUARD-001/002: the hook is generated by ``deploy_guard_configs``
    from the canonical registry; ``check_parity`` must reject any
    ``--exit-zero`` injection. The stub raises NotImplementedError -> legal Red.
    """
    registry = load_guard_registry(ARCH)
    # The registry must validate (eight categories, fail_closed, no --exit-zero).
    errors = validate_guard_registry(registry, REPO)
    assert errors == (), f"canonical registry must validate clean: {errors}"
    # No guard entry may carry --exit-zero in its command (hard gate).
    for entry in registry.entries:
        assert "--exit-zero" not in " ".join(entry.command), (
            f"guard {entry.guard_id} command must not use --exit-zero (hard gate)"
        )
        assert entry.failure_policy == "fail_closed"
    # The deployed hook must embed the registry digest and reject violations
    # (non-zero) without --exit-zero.
    target = tmp_path / "fresh"
    target.mkdir()
    deploy_guard_configs(registry, target)
    hook = target / ".githooks" / "pre-commit"
    hook_text = hook.read_text(encoding="utf-8") if hook.exists() else ""
    assert "--exit-zero" not in hook_text, (
        "deployed pre-commit hook must not use --exit-zero (hard gate)"
    )
    assert registry.digest in hook_text, "hook must embed TRACKS_GUARD_REGISTRY"
    # check_parity must block any --exit-zero injection (no soft guard).
    exit_zero_commands = {
        e.required_check: (*e.command, "--exit-zero") for e in registry.entries
    }
    parity = check_parity(
        registry=registry,
        runtime_commands=exit_zero_commands,
        pre_commit_path=hook,
        ci_workflow_path=target / ".github" / "workflows" / "ci.yml",
        cwd=target,
    )
    assert parity.mismatches, "--exit-zero injection must block parity (hard gate)"
    assert "exit_zero" in {m.kind for m in parity.mismatches}
